"""updated_at default value

Revision ID: af2a56c14107
Revises: 9ae2590a8b45
Create Date: 2023-02-03 19:33:08.070301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af2a56c14107'
down_revision = '9ae2590a8b45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
